# Running the app 

```{r}
#| eval: true 
#| echo: false 
#| include: false
source("_common.R")
```

```{r}
#| label: co_box_dev
#| echo: false
#| results: asis
#| eval: true
co_box(
  color = "r",
  header = "ALERT!",
  contents = "This section is currently under development. Thank you for your patience."
)
```

## App-package contents 

Let's review the files and folders in shiny app-packages.

### [`DESCRIPTION`]{style="font-size: 1.05em"}

```{bash}
#| eval: false
#| code-fold: false
pkgApp/
  └── DESCRIPTION
```


### [`NAMESPACE`]{style="font-size: 1.05em"}

```{bash}
#| eval: false
#| code-fold: false
pkgApp/
  └── NAMESPACE
```

### [`R/`]{style="font-size: 1.05em"} folder

```{bash}
#| eval: false
#| code-fold: false
pkgApp/
  └── R/
  
```

### [`man/`]{style="font-size: 1.05em"} folder

```{bash}
#| eval: false
#| code-fold: false
pkgApp/
  └── man/
  
```

### [`data/`]{style="font-size: 1.05em"} folder

```{bash}
#| eval: false
#| code-fold: false
pkgApp/
  └── data/
  
```


    

```{r}
#| eval: false 
#| code-fold: false
runApp()
```

[`loadSupport`]{style="font-size: 1.10em"} warning

```{bash}
#| eval: false 
#| code-fold: false
Warning in loadSupport(appDir, renv = sharedEnv, globalrenv = NULL) :
  Loading R/ subdirectory for Shiny application, but this directory appears to
contain an R package. Sourcing files in R/ may cause unexpected behavior.
```
